package com.younchen.chat.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FRIENDS.
 */
public class Friends {

    private long id;
    private String ownerId;
    private String realName;
    private Integer sex;
    private Integer age;
    private String headImg;
    private String moto;
    private String birthDay;
    private String phone;

    public Friends() {
    }

    public Friends(long id) {
        this.id = id;
    }

    public Friends(long id, String ownerId, String realName, Integer sex, Integer age, String headImg, String moto, String birthDay, String phone) {
        this.id = id;
        this.ownerId = ownerId;
        this.realName = realName;
        this.sex = sex;
        this.age = age;
        this.headImg = headImg;
        this.moto = moto;
        this.birthDay = birthDay;
        this.phone = phone;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getOwnerId() {
        return ownerId;
    }

    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId;
    }

    public String getRealName() {
        return realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getHeadImg() {
        return headImg;
    }

    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    public String getMoto() {
        return moto;
    }

    public void setMoto(String moto) {
        this.moto = moto;
    }

    public String getBirthDay() {
        return birthDay;
    }

    public void setBirthDay(String birthDay) {
        this.birthDay = birthDay;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

}
