package com.younchen.chat.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table USER.
 */
public class User {

    private long id;
    private String nickName;
    private String realName;
    private Integer sex;
    private Integer age;
    private String headImg;
    private String moto;
    private String birthDay;
    private String phone;
    private String password;

    public User() {
    }

    public User(long id) {
        this.id = id;
    }

    public User(long id, String nickName, String realName, Integer sex, Integer age, String headImg, String moto, String birthDay, String phone, String password) {
        this.id = id;
        this.nickName = nickName;
        this.realName = realName;
        this.sex = sex;
        this.age = age;
        this.headImg = headImg;
        this.moto = moto;
        this.birthDay = birthDay;
        this.phone = phone;
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getRealName() {
        return realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getHeadImg() {
        return headImg;
    }

    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    public String getMoto() {
        return moto;
    }

    public void setMoto(String moto) {
        this.moto = moto;
    }

    public String getBirthDay() {
        return birthDay;
    }

    public void setBirthDay(String birthDay) {
        this.birthDay = birthDay;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
